"""
app.py — Provenance Guard
Flask API for AI content attribution.

Endpoints:
    POST /submit   — classify text content
    POST /appeal   — contest a classification
    GET  /log      — view audit log entries
"""

import json
import math
import os
import re
import sqlite3
import string
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

# ── Rate limiting ─────────────────────────────────────────────────────────────
# 10/minute: a real creator submits work at most a few times per session,
# not 10+ times per minute. This blocks scripted flooding while allowing
# legitimate bursts (e.g., testing a few variants of a piece).
# 100/day: generous enough for any individual creator; a script hitting
# this limit is almost certainly abuse.
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Database setup ────────────────────────────────────────────────────────────
DB_PATH = "provenance.db"

def init_db():
    """Create the audit log table if it doesn't exist."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            content_id       TEXT PRIMARY KEY,
            creator_id       TEXT NOT NULL,
            timestamp        TEXT NOT NULL,
            text_preview     TEXT,
            attribution      TEXT NOT NULL,
            confidence       REAL NOT NULL,
            llm_score        REAL NOT NULL,
            stylometric_score REAL NOT NULL,
            label_text       TEXT NOT NULL,
            status           TEXT NOT NULL DEFAULT 'classified',
            appeal_reasoning TEXT,
            appeal_timestamp TEXT
        )
    """)
    conn.commit()
    conn.close()

init_db()


# ── Signal 1: LLM Classifier ──────────────────────────────────────────────────

def classify_with_llm(text: str) -> float:
    """
    Ask Groq's LLM to assess whether text is AI-generated or human-written.

    Returns a float 0.0–1.0 where 1.0 = maximally AI-like.
    Returns 0.5 on any parsing failure (uncertain fallback).
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("[LLM] No API key — returning 0.5 fallback")
        return 0.5

    try:
        client = Groq(api_key=api_key)
        prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and estimate the probability that it was generated by an AI writing tool (rather than written by a human).

Consider:
- Vocabulary uniformity and predictability
- Sentence structure variation (or lack thereof)
- Presence of hedging phrases typical of AI ("it is important to note", "furthermore", "in conclusion")
- Natural imperfections, casual register, or emotional authenticity typical of humans
- Overall stylistic coherence and "polish"

Text to analyze:
\"\"\"
{text[:2000]}
\"\"\"

Respond with ONLY a JSON object in this exact format, nothing else:
{{"ai_probability": 0.XX}}

Where 0.XX is a float between 0.00 (definitely human) and 1.00 (definitely AI)."""

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        raw = response.choices[0].message.content.strip()
        # Parse JSON response
        match = re.search(r'\{[^}]+\}', raw)
        if match:
            data = json.loads(match.group())
            score = float(data.get("ai_probability", 0.5))
            return max(0.0, min(1.0, score))
        return 0.5

    except Exception as e:
        print(f"[LLM] Error: {e}")
        return 0.5


# ── Signal 2: Stylometric Heuristics ─────────────────────────────────────────

def compute_stylometric_score(text: str) -> float:
    """
    Compute a stylometric AI-likelihood score based on three structural metrics:
    1. Sentence length variance (low variance → more AI-like)
    2. Type-token ratio / vocabulary diversity (low TTR → more AI-like)
    3. Punctuation density (very uniform density → slightly more AI-like)

    Returns a float 0.0–1.0 where 1.0 = maximally AI-like.
    Returns 0.5 for very short texts (< 20 words) — insufficient data.
    """
    words = text.split()
    if len(words) < 20:
        return 0.5  # insufficient data for stylometrics

    # ── Metric 1: Sentence length variance ───────────────────────────────────
    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    sentence_lengths = [len(s.split()) for s in sentences if s.split()]

    if len(sentence_lengths) < 2:
        slv_score = 0.5
    else:
        mean_len = sum(sentence_lengths) / len(sentence_lengths)
        variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
        std_dev = math.sqrt(variance)
        # Normalize: std_dev of 0 (perfect uniformity) → 1.0 (AI-like)
        # std_dev of 10+ (high variance) → 0.0 (human-like)
        # Using sigmoid-like normalization capped at std_dev=15
        slv_score = max(0.0, 1.0 - min(std_dev / 12.0, 1.0))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ────────────────────
    word_tokens = [w.lower().strip(string.punctuation) for w in words]
    word_tokens = [w for w in word_tokens if w]
    if not word_tokens:
        ttr_score = 0.5
    else:
        unique_words = set(word_tokens)
        ttr = len(unique_words) / len(word_tokens)
        # Low TTR (e.g., 0.4) → AI-like → score near 1.0
        # High TTR (e.g., 0.8) → human-like → score near 0.0
        # Typical AI TTR ~0.45–0.60; human TTR ~0.60–0.80
        ttr_score = max(0.0, min(1.0, (0.75 - ttr) / 0.40))

    # ── Metric 3: Punctuation density ────────────────────────────────────────
    punct_chars = sum(1 for c in text if c in string.punctuation)
    total_chars = len(text.replace(" ", ""))
    if total_chars == 0:
        pd_score = 0.5
    else:
        punct_density = punct_chars / total_chars
        # AI text tends to have moderate, consistent punctuation (0.05–0.12)
        # Human text varies more — may be very low (stream-of-consciousness)
        # or very high (heavy quotation/citation)
        # Score: density in 0.05–0.12 range → slightly AI-like
        if 0.04 <= punct_density <= 0.13:
            pd_score = 0.6
        else:
            pd_score = 0.35

    # ── Combine three metrics ─────────────────────────────────────────────────
    # Sentence length variance is most reliable; TTR second; punctuation weakest
    combined = (0.50 * slv_score) + (0.35 * ttr_score) + (0.15 * pd_score)
    return max(0.0, min(1.0, combined))


# ── Confidence scoring ────────────────────────────────────────────────────────

def compute_confidence(llm_score: float, stylometric_score: float) -> float:
    """
    Combine two signal scores into a single confidence score.
    LLM signal is weighted more heavily (semantic > structural for short texts).
    """
    return round((0.65 * llm_score) + (0.35 * stylometric_score), 4)


def get_attribution(confidence: float) -> str:
    """Map confidence score to attribution label."""
    if confidence >= 0.70:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


# ── Transparency label generation ─────────────────────────────────────────────

def generate_label(attribution: str, confidence: float) -> str:
    """
    Generate the transparency label text shown to end users.

    Three variants:
    - likely_ai (confidence >= 0.70): high-confidence AI label
    - uncertain (0.40 <= confidence < 0.70): uncertain label
    - likely_human (confidence < 0.40): high-confidence human label
    """
    if attribution == "likely_ai":
        pct = round(confidence * 100)
        return (
            f"⚠️ AI-Generated Content\n\n"
            f"Our system has determined with high confidence ({pct}%) that this content "
            f"was likely generated by an AI writing tool rather than written by a human author.\n\n"
            f"This classification is based on automated analysis and may not be perfect. "
            f"If you are the creator and believe this is incorrect, you can submit an appeal.\n\n"
            f"Confidence: {pct}% | Status: Classified"
        )
    elif attribution == "uncertain":
        pct = round(confidence * 100)
        return (
            f"🔍 Authorship Uncertain\n\n"
            f"Our system could not confidently determine whether this content was written "
            f"by a human or generated by an AI tool. The signals we analyzed were mixed "
            f"or inconclusive (confidence: {pct}%).\n\n"
            f"If you are the creator, you may submit an appeal to provide context about "
            f"how this content was created.\n\n"
            f"Confidence: {pct}% | Status: Classified"
        )
    else:  # likely_human
        pct = round((1 - confidence) * 100)
        return (
            f"✓ Likely Human-Written\n\n"
            f"Our system is confident ({pct}%) that this content was written by a human author.\n\n"
            f"Automated analysis can make mistakes. Readers should use their own judgment "
            f"when evaluating any content.\n\n"
            f"Confidence: {pct}% | Status: Classified"
        )


# ── Audit log helpers ─────────────────────────────────────────────────────────

def log_decision(content_id, creator_id, text, attribution,
                 confidence, llm_score, stylometric_score, label_text):
    """Write a classification decision to the audit log."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO audit_log
        (content_id, creator_id, timestamp, text_preview, attribution,
         confidence, llm_score, stylometric_score, label_text, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'classified')
    """, (
        content_id,
        creator_id,
        datetime.now(timezone.utc).isoformat(),
        text[:200],
        attribution,
        confidence,
        llm_score,
        stylometric_score,
        label_text,
    ))
    conn.commit()
    conn.close()


def log_appeal(content_id, reasoning):
    """Update an existing log entry with appeal information."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        UPDATE audit_log
        SET status = 'under_review',
            appeal_reasoning = ?,
            appeal_timestamp = ?
        WHERE content_id = ?
    """, (reasoning, datetime.now(timezone.utc).isoformat(), content_id))
    conn.commit()
    conn.close()


def get_log_entries(limit=20):
    """Return the most recent audit log entries as a list of dicts."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("""
        SELECT * FROM audit_log
        ORDER BY timestamp DESC
        LIMIT ?
    """, (limit,)).fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_entry(content_id):
    """Return a single audit log entry by content_id."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    row = conn.execute(
        "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


# ── API Endpoints ─────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    Submit text content for attribution analysis.

    Request body (JSON):
        text        (str, required) — the content to classify
        creator_id  (str, required) — identifier for the creator

    Response (JSON):
        content_id   (str)   — unique ID for this submission
        attribution  (str)   — "likely_ai", "uncertain", or "likely_human"
        confidence   (float) — combined confidence score 0.0–1.0
        llm_score    (float) — Signal 1 score
        stylometric_score (float) — Signal 2 score
        label        (str)   — full transparency label text
        status       (str)   — "classified"
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Field 'text' is required and cannot be empty"}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required"}), 400
    if len(text) < 10:
        return jsonify({"error": "Text is too short for meaningful analysis (minimum 10 characters)"}), 400

    # Generate unique content ID
    content_id = str(uuid.uuid4())

    # Run both detection signals
    llm_score = classify_with_llm(text)
    stylometric_score = compute_stylometric_score(text)

    # Compute combined confidence and attribution
    confidence = compute_confidence(llm_score, stylometric_score)
    attribution = get_attribution(confidence)
    label = generate_label(attribution, confidence)

    # Write to audit log
    log_decision(
        content_id=content_id,
        creator_id=creator_id,
        text=text,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        stylometric_score=stylometric_score,
        label_text=label,
    )

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label,
        "status": "classified",
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    Submit an appeal for a contested classification.

    Request body (JSON):
        content_id        (str, required) — ID from the original /submit response
        creator_reasoning (str, required) — creator's explanation

    Response (JSON):
        content_id (str)  — confirmed content ID
        status     (str)  — "under_review"
        message    (str)  — confirmation message
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Field 'content_id' is required"}), 400
    if not reasoning:
        return jsonify({"error": "Field 'creator_reasoning' is required"}), 400

    # Check content exists
    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404

    if entry["status"] == "under_review":
        return jsonify({
            "content_id": content_id,
            "status": "under_review",
            "message": "An appeal has already been filed for this content and is under review.",
        }), 200

    # Update status and log appeal
    log_appeal(content_id, reasoning)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": (
            "Your appeal has been received and the content has been marked for human review. "
            "A reviewer will examine both the original classification and your reasoning. "
            "No automated re-classification will occur."
        ),
        "original_attribution": entry["attribution"],
        "original_confidence": entry["confidence"],
    }), 200


@app.route("/log", methods=["GET"])
def log():
    """
    Return recent audit log entries.

    Query params:
        limit (int, optional) — number of entries to return (default 20, max 100)

    Response (JSON):
        entries (list) — list of audit log entry dicts
        count   (int)  — number of entries returned
    """
    try:
        limit = min(int(request.args.get("limit", 20)), 100)
    except ValueError:
        limit = 20

    entries = get_log_entries(limit)
    return jsonify({
        "entries": entries,
        "count": len(entries),
    }), 200


@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error": "Rate limit exceeded",
        "message": "You have submitted too many requests. Limit: 10 per minute, 100 per day.",
        "retry_after": "Please wait before submitting again.",
    }), 429


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True, port=5000)
